### ISSUE TITLE
Chrome Extension: Migrate to Vue.js setup with Webpack and NPM (lol this will never happen) (ay larmbox) (can somebody remove this lolissue?) (hey nathan if you're ever on here remove this)

### ISSUE THREAD

**Issue by FilmCoder** [FilmCoder/Slormuxify#5]
Right now we're just coding everything in Vanilla JS, but I'd like to pull Vue.js in along with webpack and NPM to keep things cleaner.

With Vue.JS/webpack, we can design the popup UI in a cleaner way,
and with NPM we can manage dependencies automically without downloading libraries manually and storing them in the libraries folder.

Instructions: https://www.sitepoint.com/build-vue-chrome-extension/

I think this will basically required a complete startover, most likely I'll start from scratch and override everything.  The issue is that the hierarchy of all the files will change.

**Comment by FilmCoder** [comment]
One thing this will change is that instead of being able to open the chrome_extension folder directly, we'd need to "build" our chrome_extension with webpack into a /build folder, and then open that build folder with Chrome.  Because Chrome won't know how to deal with .Vue files.

**Comment by FilmCoder** [comment]
nathan once you click the close button below i'll know you've have done something lel.  we'll use the number of days old this comment is as a tracker.

**Comment by smittostuff** [comment]
Don't worry buddy, I'm on it! Thanks for the heads up!
